name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Check for broken links
      run: |
        # Install link checker
        pip install linkchecker
        # Run link checker
        linkchecker docs/index.md
